config:
  data:
    data_dir: D:\\data_cache
    end_date: '2023-12-31'
    start_date: '2020-01-01'
    symbols:
    - BTCUSDT
    - ETHUSDT
    test_ratio: 0.15
    timeframe: 1h
    train_ratio: 0.7
    val_ratio: 0.15
  env:
    commission_rate: 0.0005190913496713061
    curiosity_coef: 0.01
    delta_time_penalty: 0.001
    drawdown_penalty: 0.1
    end_episode_penalty: 0.1
    holding_cost_alpha: 0.0001
    initial_balance: 9668
    max_drawdown_threshold: 0.1
    max_position: 0.44525462771666846
    min_trade_threshold: 0.04098218166285739
    min_trades_per_episode: 5
    reward_scaling: 0.09300233441119435
    running_mean_window: 50
    running_std_window: 15
    slippage: 0.0005255365074374468
    stop_loss: 0.031927803773529474
    take_profit: 0.031131021049891006
    trade_execution_bonus: 0.01
  evaluation:
    test_end_date: '2023-12-31'
    test_start_date: '2022-01-01'
  features:
    ema_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
    sequence_length: 60
    sma_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
    timeframes:
    - 1h
    - 2h
    - 4h
    - 12h
    - 24h
    - 7d
  model:
    batch_size: 475
    clip_ratio: 0.1930766047354013
    entropy_coef: 0.028086127053917276
    gae_lambda: 0.9138395084839694
    gamma: 0.9138797920933
    learning_rate: 0.0002550003133175639
    max_grad_norm: 0.4173941384684435
    n_epochs: 9
    n_steps: 3865
    value_coef: 0.6274365608269078
  training:
    eval_freq: 10000
    n_eval_episodes: 5
    tensorboard_log: logs/tensorboard
    total_timesteps: 1000000
fitness: -.inf
generation: 0
timestamp: '20250516_115132'
