config:
  data:
    data_dir: D:\\data_cache
    end_date: '2023-12-31'
    start_date: '2020-01-01'
    symbols:
    - BTCUSDT
    - ETHUSDT
    test_ratio: 0.15
    timeframe: 1h
    train_ratio: 0.7
    val_ratio: 0.15
  env:
    commission_rate: 0.0005051711572628847
    curiosity_coef: 0.01
    delta_time_penalty: 0.001
    drawdown_penalty: 0.1
    end_episode_penalty: 0.1
    holding_cost_alpha: 0.0001
    initial_balance: 1132
    max_drawdown_threshold: 0.1
    max_position: 0.7256275500240373
    min_trade_threshold: 0.0916967276412065
    min_trades_per_episode: 5
    reward_scaling: 0.09201355563736925
    running_mean_window: 12
    running_std_window: 36
    slippage: 0.00011919270953067416
    stop_loss: 0.047427674448577956
    take_profit: 0.041250321569160406
    trade_execution_bonus: 0.01
  evaluation:
    test_end_date: '2023-12-31'
    test_start_date: '2022-01-01'
  features:
    ema_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
    sequence_length: 60
    sma_periods:
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
    timeframes:
    - 1h
    - 2h
    - 4h
    - 12h
    - 24h
    - 7d
  model:
    batch_size: 62
    clip_ratio: 0.2326623192754306
    entropy_coef: 0.08650311377913164
    gae_lambda: 0.9680421949113533
    gamma: 0.9267573052680029
    learning_rate: 0.0008962647295335717
    max_grad_norm: 0.6014619415310483
    n_epochs: 12
    n_steps: 2121
    value_coef: 0.8277963058088011
  training:
    eval_freq: 10000
    n_eval_episodes: 5
    tensorboard_log: logs/tensorboard
    total_timesteps: 1000000
fitness: -.inf
generation: 0
timestamp: '20250516_115814'
