# Model configuration
model:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  entropy_coef: 0.01
  value_coef: 0.5
  max_grad_norm: 0.5

# Environment configuration
env:
  initial_balance: 10000
  commission_rate: 0.001
  slippage: 0.0005
  max_position: 1.0
  reward_scaling: 0.01
  min_trade_threshold: 0.1
  stop_loss: 0.02
  take_profit: 0.04
  running_mean_window: 100
  running_std_window: 100
  delta_time_penalty: 0.001
  trade_execution_bonus: 0.01
  holding_cost_alpha: 0.0001
  max_drawdown_threshold: 0.1
  drawdown_penalty: 0.1
  min_trades_per_episode: 5
  end_episode_penalty: 0.1
  curiosity_coef: 0.01

# Feature engineering configuration
features:
  sequence_length: 60
  timeframes: ['1h', '2h', '4h', '12h', '24h', '7d']
  sma_periods: [5, 10, 20, 50, 100, 200]
  ema_periods: [5, 10, 20, 50, 100, 200]

# Training configuration
training:
  total_timesteps: 1000000
  eval_freq: 10000
  n_eval_episodes: 5
  tensorboard_log: "logs/tensorboard"

# Data configuration
data:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  symbols: ['BTCUSDT', 'ETHUSDT']
  timeframe: '1h'
  start_date: '2020-01-01'
  end_date: '2023-12-31'
  data_dir: 'D:\\data_cache'  # Directory containing the data files

evaluation:
  test_start_date: '2022-01-01'
  test_end_date: '2023-12-31' 